version: '3.9'
services:
  db:
    image: postgres:13.7-alpine
    container_name: db
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: 'always'
    healthcheck:
      test: ["CMD-SHELL", "sh -c", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s