version: '3.9'
services:
  db:
    image: postgres:13.7-alpine
    container_name: db
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bravi_contacts
    restart: 'always'